# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('people', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('publish_time', models.CharField(max_length=30)),
                ('ip', models.CharField(default='-', max_length=50)),
                ('time', models.CharField(default='-', max_length=20)),
                ('size', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=80)),
                ('publish_time', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('ip', models.CharField(default='-', max_length=50)),
                ('time', models.CharField(default='-', max_length=20)),
                ('size', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
