# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='addDate',
        ),
        migrations.RemoveField(
            model_name='server',
            name='lastDate',
        ),
    ]
